import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
library.add(fas);

export { default as Alert } from './components/Alert';
export { default as AutoComplete } from './components/AutoComplete';
export { default as Avatar } from './components/Avatar';
export { default as Button } from './components/Button';
export { default as Card } from './components/Card';
export { default as Carousel } from './components/Carousel';
export { default as Divider } from './components/Divider';
export { default as Empty } from './components/Empty';
export { default as Icon } from './components/Icon';
export { default as Image } from './components/Image';
export { default as Input } from './components/Input';
export { default as Layout } from './components/Layout';
export { default as Menu } from './components/Menu';
export { default as PageHeader } from './components/PageHeader';
export { default as Progress } from './components/Progress';
export { default as Tabs } from './components/Tabs';
export { default as Transition } from './components/Transition';
export { default as Upload } from './components/Upload';
